
# Define variables (example from your previous code)
clustering_variables_dict = {                      'top_vars3_eT_pci3':  [
                  'ethnic_group_perc_White: English, Welsh, Scottish, Northern Irish or British',
                    'clean_res_total_fl_area_H_total',
                    'all_res_total_buildings', 
                    'clean_res_uprn_count_total',
                    'CDD' ,
                    'HDD',
                    'postcode_density',
                    'Post 1999_pct',
                    'Pre 1919_pct',
                       'deprivation_perc_Household is deprived in two dimensions',
                       'economic_activity_perc_Economically inactive: Student',
                       'economic_activity_perc_Economically active (excluding full-time students): In employment: Employee: Full-time',
                       'economic_activity_perc_Economically inactive: Retired',
                        'Domestic outbuilding_pct',
                     'total_energy',
                     'PCI',
                        
            ] ,
            'top_vars':  [
                  'ethnic_group_perc_White: English, Welsh, Scottish, Northern Irish or British',
                    'clean_res_total_fl_area_H_total',
                    'all_res_total_buildings', 
                    'clean_res_uprn_count_total',
                    'CDD' ,
                    'HDD',
                    'postcode_density',
                    'Post 1999_pct',
                    'Pre 1919_pct',
            ] ,
                  'top_vars3': [
                  'ethnic_group_perc_White: English, Welsh, Scottish, Northern Irish or British',
                    'clean_res_total_fl_area_H_total',
                    'all_res_total_buildings', 
                    'clean_res_uprn_count_total',
                    'CDD' ,
                    'HDD',
                    'postcode_density',
                    'Post 1999_pct',
                    'Pre 1919_pct',
                       'deprivation_perc_Household is deprived in two dimensions',
                       'economic_activity_perc_Economically inactive: Student',
                        'Domestic outbuilding_pct',
                  ],
                  
         
                'top_vars_e':  [
                  'ethnic_group_perc_White: English, Welsh, Scottish, Northern Irish or British',
                    'clean_res_total_fl_area_H_total',
                    'all_res_total_buildings', 
                    'clean_res_uprn_count_total',
                    'CDD' ,
                    'HDD',
                    'postcode_density',
                    'Post 1999_pct',
                    'Pre 1919_pct',
                       'total_gas',
                        'total_elec',
            ] ,
                 'tv_eui':  [
                  'ethnic_group_perc_White: English, Welsh, Scottish, Northern Irish or British',
                    'clean_res_total_fl_area_H_total',
                    'all_res_total_buildings', 
                    'clean_res_uprn_count_total',
                    'CDD' ,
                    'HDD',
                    'postcode_density',
                    'Post 1999_pct',
                    'Pre 1919_pct',
                       'gas_EUI_H',
                        'elec_EUI_H',
            ] ,

  
            
             'top_vars3_e' :
                  [ 'ethnic_group_perc_White: English, Welsh, Scottish, Northern Irish or British',
                    'clean_res_total_fl_area_H_total',
                    'all_res_total_buildings', 
                    'clean_res_uprn_count_total',
                    'CDD' ,
                    'HDD',
                    'postcode_density',
                    'Post 1999_pct',
                    'Pre 1919_pct',
                       'deprivation_perc_Household is deprived in two dimensions',
                       'economic_activity_perc_Economically inactive: Student',
                        'Domestic outbuilding_pct',
                     'total_gas',
                        'total_elec',
            ] ,
                 'tv3_eui':  [
                  'ethnic_group_perc_White: English, Welsh, Scottish, Northern Irish or British',
                    'clean_res_total_fl_area_H_total',
                    'all_res_total_buildings', 
                    'clean_res_uprn_count_total',
                    'CDD' ,
                    'HDD',
                    'postcode_density',
                    'Post 1999_pct',
                    'Pre 1919_pct',
                       'deprivation_perc_Household is deprived in two dimensions',
                       'economic_activity_perc_Economically inactive: Student',
                        'Domestic outbuilding_pct',
                     'gas_EUI_H',
                        'elec_EUI_H',
            ] ,
                               'top_vars3_eT_pci':  [
                  'ethnic_group_perc_White: English, Welsh, Scottish, Northern Irish or British',
                    'clean_res_total_fl_area_H_total',
                    'all_res_total_buildings', 
                    'clean_res_uprn_count_total',
                    'CDD' ,
                    'HDD',
                    'postcode_density',
                    'Post 1999_pct',
                    'Pre 1919_pct',
                       'deprivation_perc_Household is deprived in two dimensions',
                       'economic_activity_perc_Economically inactive: Student',
                        'Domestic outbuilding_pct',
                     'total_energy',
                     'PCI',
                        
            ] ,
                         'tv3_eui_eth':  [
                  'ethnic_group_perc_White: English, Welsh, Scottish, Northern Irish or British',
                    'clean_res_total_fl_area_H_total',
                    'all_res_total_buildings', 
                    'clean_res_uprn_count_total',
                    'CDD' ,
                    'HDD',
                    'postcode_density',
                    'Post 1999_pct',
                    'Pre 1919_pct',
                       'economic_activity_perc_Economically active (excluding full-time students): In employment: Employee: Full-time',
                       'economic_activity_perc_Economically inactive: Student',
                        'economic_activity_perc_Economically inactive: Retired',
                         'economic_activity_perc_Economically active (excluding full-time students): Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks',
                        'Domestic outbuilding_pct',
                        
                     'gas_EUI_H',
                        'elec_EUI_H',
            ],
            
             'top_vars3_e_eth':  [
                  'ethnic_group_perc_White: English, Welsh, Scottish, Northern Irish or British',
                    'clean_res_total_fl_area_H_total',
                    'all_res_total_buildings', 
                    'clean_res_uprn_count_total',
                    'CDD' ,
                    'HDD',
                    'postcode_density',
                    'Post 1999_pct',
                    'Pre 1919_pct',
                       'economic_activity_perc_Economically active (excluding full-time students): In employment: Employee: Full-time',
                       'economic_activity_perc_Economically inactive: Student',
                        'economic_activity_perc_Economically inactive: Retired',
                         'economic_activity_perc_Economically active and a full-time student: Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks',
                       
                        'Domestic outbuilding_pct',
                     'total_gas',
                        'total_elec',
            ] ,
                         'top_vars3_e_eth2':  [
                  'ethnic_group_perc_White: English, Welsh, Scottish, Northern Irish or British',
                    'clean_res_total_fl_area_H_total',
                    'all_res_total_buildings', 
                    'clean_res_uprn_count_total',
                    'CDD' ,
                    'HDD',
                    'postcode_density',
                    'Post 1999_pct',
                    'Pre 1919_pct',
                       'economic_activity_perc_Economically active (excluding full-time students): In employment: Employee: Full-time',
                       'economic_activity_perc_Economically inactive: Student',
                        'economic_activity_perc_Economically inactive: Retired',
                         'economic_activity_perc_Economically active (excluding full-time students): Unemployed: Seeking work or waiting to start a job already obtained: Available to start working within 2 weeks',
                       
                        'Domestic outbuilding_pct',
                     'total_gas',
                        'total_elec',
            ] ,
                         'top_vars3_eT2':   [
                  'ethnic_group_perc_White: English, Welsh, Scottish, Northern Irish or British',
                    'clean_res_total_fl_area_H_total',
                    'all_res_total_buildings', 
                    'clean_res_uprn_count_total',
                    'CDD' ,
                    'HDD',
                    'postcode_density',
                    'Post 1999_pct',
                    'Pre 1919_pct',
                       'deprivation_perc_Household is deprived in two dimensions',
                       'economic_activity_perc_Economically inactive: Student',
                         'economic_activity_perc_Economically active (excluding full-time students): In employment: Employee: Full-time',
                        'Domestic outbuilding_pct',
                     'total_energy',
                        
            ] ,
                                     'top_vars3_eT_pci2':  [
                  'ethnic_group_perc_White: English, Welsh, Scottish, Northern Irish or British',
                    'clean_res_total_fl_area_H_total',
                    'all_res_total_buildings', 
                    'clean_res_uprn_count_total',
                    'CDD' ,
                    'HDD',
                    'postcode_density',
                    'Post 1999_pct',
                    'Pre 1919_pct',
                       'deprivation_perc_Household is deprived in two dimensions',
                       'economic_activity_perc_Economically inactive: Student',
                       'economic_activity_perc_Economically active (excluding full-time students): In employment: Employee: Full-time',
                        'Domestic outbuilding_pct',
                     'total_energy',
                     'PCI',
                        
            ] ,
           
        }